package llm

import (
	"encoding/json"
	"fmt"
	"strings"
)

// buildSystemPrompt constructs the system prompt, optionally with a persona
func buildSystemPrompt(persona string) string {
	base := `You are playing the word association game Unanimo. Your goal is to think of words that OTHER AI models would ALSO think of, maximizing shared responses and scoring the most points.`
	if persona != "" {
		return base + "\n\n" + persona
	}
	return base
}

// buildWordPrompt constructs the user prompt for word generation
func buildWordPrompt(concept string) string {
	return fmt.Sprintf(`The concept card for this round is: "%s"

List exactly 8 single words that immediately come to mind when you think of "%s".

Rules:
- Single words ONLY (no phrases, hyphenated words, or compound words)
- Do NOT use words with the same root as "%s" (e.g., if concept is "run", avoid "running", "runner")
- Do NOT use numbers or symbols
- Think of the MOST COMMON, OBVIOUS associations — the ones other AI models would also think of
- Prioritize high-frequency, universal associations over creative or unusual ones

Respond with ONLY a valid JSON array of exactly 8 words. No explanation, no markdown, no extra text.
Example format: ["word1", "word2", "word3", "word4", "word5", "word6", "word7", "word8"]`, concept, concept, concept)
}

// judgeSystemPrompt returns the system prompt for the judge role
func judgeSystemPrompt() string {
	return `You are a semantic judge for the Unanimo word game. Your task is to group words into semantic clusters based on meaning similarity. Words that are synonyms, plurals, or conceptually equivalent should share the same cluster ID.`
}

// buildJudgePrompt constructs the prompt for semantic clustering
func buildJudgePrompt(words []string, concept string) string {
	wordList := strings.Join(words, ", ")
	return fmt.Sprintf(`The game concept was: "%s"

These words were generated by different AI models:
%s

Group these words into semantic clusters. Words that mean the same thing, are plurals of each other, or are conceptually very close should share the same cluster ID number.

Rules:
- Assign integer cluster IDs starting from 1
- Exact synonyms and plurals MUST be in the same cluster
- Very closely related words (e.g., "ocean"/"sea", "happy"/"joyful") should be in the same cluster
- Loosely related words should be in DIFFERENT clusters
- Each unique concept gets its own cluster ID

Respond with ONLY a valid JSON object mapping each word to its cluster ID.
Example: {"cat": 1, "cats": 1, "feline": 1, "dog": 2, "canine": 2, "fish": 3}

Include ALL words from the input list.`, concept, wordList)
}

// parseWordsFromJSON extracts a string slice from a JSON array response
// Handles cases where the model wraps the array in markdown code blocks
func parseWordsFromJSON(raw string) ([]string, error) {
	// Strip markdown code blocks if present
	raw = strings.TrimPrefix(raw, "```json")
	raw = strings.TrimPrefix(raw, "```")
	raw = strings.TrimSuffix(raw, "```")
	raw = strings.TrimSpace(raw)

	// Find the JSON array
	start := strings.Index(raw, "[")
	end := strings.LastIndex(raw, "]")
	if start == -1 || end == -1 || end <= start {
		return nil, fmt.Errorf("no JSON array found in response: %q", raw)
	}
	raw = raw[start : end+1]

	var words []string
	if err := json.Unmarshal([]byte(raw), &words); err != nil {
		return nil, fmt.Errorf("parse JSON array: %w (raw: %q)", err, raw)
	}

	// Validate and clean words
	var result []string
	for _, w := range words {
		w = strings.TrimSpace(w)
		if w != "" {
			result = append(result, w)
		}
	}

	if len(result) == 0 {
		return nil, fmt.Errorf("no valid words found")
	}

	// Truncate to 8 if more were returned
	if len(result) > 8 {
		result = result[:8]
	}

	return result, nil
}

// parseClusterResponse extracts a word->cluster_id map from a JSON object response
func parseClusterResponse(raw string) (map[string]int, error) {
	// Strip markdown
	raw = strings.TrimPrefix(raw, "```json")
	raw = strings.TrimPrefix(raw, "```")
	raw = strings.TrimSuffix(raw, "```")
	raw = strings.TrimSpace(raw)

	// Find the JSON object
	start := strings.Index(raw, "{")
	end := strings.LastIndex(raw, "}")
	if start == -1 || end == -1 || end <= start {
		return nil, fmt.Errorf("no JSON object found in response: %q", raw)
	}
	raw = raw[start : end+1]

	var clusters map[string]int
	if err := json.Unmarshal([]byte(raw), &clusters); err != nil {
		// Try parsing as map[string]float64 (JSON numbers)
		var floatClusters map[string]float64
		if err2 := json.Unmarshal([]byte(raw), &floatClusters); err2 != nil {
			return nil, fmt.Errorf("parse cluster JSON: %w", err)
		}
		clusters = make(map[string]int)
		for k, v := range floatClusters {
			clusters[k] = int(v)
		}
	}

	return clusters, nil
}
